### ISSUE TITLE
Deployment Probleme

### ISSUE THREAD

**Issue by bockstaller** [iued-heidelberg/hueb#84]
Hi @annadymanus ,
anscheinend folge ich dem Projekt aus versehen noch und mir sind deine Commits das Deployment zum laufen zu bekommen aufgefallen.

027f054ee4f049fe94e082c9eaead499c4bb2846 Richtig erkannt, die Releases müssen v*.*.* [benannt]((https://github.com/iued-heidelberg/hueb#:~:text=A%20deployment%20to%20hueb.iued.uni-heidelberg.de%20is%20triggered%20by%20pushing%20a%20tag%20with%20the%20structure%20v*.*.*%20and%20runs%20the%20same%20steps%20as%20for%20staging.%20It%20uses%20the%20tags%3A%20TODO%20for%20its%20docker%20images%20and%20adds%20two%20steps%20to%20publish%20release%20notifications%20to%20Sentry%20and%20Honeycomb.)) sein 

a56dbc16e6740f1be6030ef53ebbef4ac1112805 Um die Probleme mit Black zu umgehen, ist der [Schritt ](https://github.com/iued-heidelberg/hueb#:~:text=pip3%20install%20-r%20requirements.txt%0Apre-commit%20install) wichtig. Dann laufen Black und die anderen Formatier-Tools vor jedem Commit, aktualisierte Dateien musst du dann mit `git add` hinzufügen und nochmal den Commit versuchen

Soweit ich das sehe waren das die Hauptproblem.
Dein letzter Versuch 3898cc27f2737bfed25a0b9994eb9fa86b5a8636 hätte ohne Probleme durchlaufen sollen. Allerdings hat Github sich wohl in einem [Schritt verschluckt](https://github.com/iued-heidelberg/hueb/runs/3720642515#step:5:84).
Mit einem Klick auf Re-run Jobs sollte sich das lösen

**Comment by annadymanus** [comment]
Hi @bockstaller ,

danke dir. Ja, ich hab mich ein bisschen dumm angestellt (etwas peinlich) :)Ich dachte das Black prüft ja nur style und hab erst sehr spät bemerkt dass es abbricht wenn es den Test nicht besteht. Ich hatte das erst als Fehlerursache ausgeschlossen weil trotz dem Black Fehler hat es letzte woche bei hueb-staging funktioniert.

Sry dass ich mit dem commit wahnsinn das repository ein bisschen verunstaltet habe^^ 

Vielen vielen Dank für deine Hilfe!

**Comment by bockstaller** [comment]
Hi @annadymanus,

das ist jetzt dein Projekt :) 
Du wirst wahrscheinlich noch genügend Arbeit finden die ich dir hinterlassen habe 😅.  Wenn was nicht taugt oder du ein cleveren Ansatz hast ersetz es einfach. Mein Ego hängt da nicht dran.

Ich hab meinen Stand für den Lebenslauf gesichert und aufgeschrieben was ich in dem Projekt gemacht habe - würde ich an deiner Stelle auch nebenher mitschreiben

**Comment by bockstaller** [comment]
I'm closing this issue as I am no longer working on this project, the issue tracker is not actively used, and want to clean up my personal github account
